name: tebooka
description: "TEBOOKA Real-Time Bus Booking App"
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=3.4.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.2.2
  flutter_launcher_icons: ^0.13.1
  
  lottie: ^2.7.0
  firebase_core: ^2.28.0
  firebase_auth: ^4.17.8
  cloud_firestore: ^4.17.0
  google_maps_flutter: ^2.5.0
  geolocator: ^11.0.0
  location: ^5.0.3
  geocoding: ^2.1.0
  uuid: ^4.2.1
  google_place: ^0.4.7
  
  vector_math: ^2.1.2
  barcode_widget: ^2.0.1
  
  cupertino_icons: ^1.0.6
  image_picker: ^1.0.7
  firebase_storage: ^11.6.6
  url_launcher: ^6.2.6
  font_awesome_flutter: ^10.7.0
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/man.jpg
    - assets/bpr.jpg
    - assets/liberation.jpg
    - assets/pinnacle.jpg
    - assets/town.jpg
    - assets/amahoro.jpg  

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/logo.jpg"