name: tebooka
description: "TEBOOKA Real-Time Bus Booking App"
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=3.4.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.2.2
  lottie: ^2.7.0
  firebase_core: ^2.28.0
  firebase_auth: ^4.17.8

  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - lib/assets/land_image.jpg  
